export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
}

export default function MarketingLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <body>
            <header>
                <p>header</p>
            </header>
            {children}
            <footer>
                <p>footer</p>
            </footer>
        </body>
    )
}